name: Publicar no PyPI

on:
  push:
    tags:
      - "v0.1.1"  

permissions:
  id-token: write  
  contents: read

jobs:
  build-and-publish:
    name: Build e Publicar
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependências de build
        run: |
          pip install build

      - name: Build do pacote
        run: |
          python -m build

      - name: Publicar no PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
